### ISSUE TITLE
Screen sharing frozen at approximately 39 minutes after the hour

### ISSUE THREAD

**Issue by glennon** [githubteacher/desktop-project#18]
Anyone else -- or just me? <b>_update: it was just me_</b>

**Comment by glennon** [comment]
ps -- audio continued, just not what was happening on screen.

**Comment by primercuervo** [comment]
Not the case for me, working fine.

**Comment by glennon** [comment]
thanks @primercuervo. just me then. I know my way around forking, so all good. (solution: had to refresh my gotowebinar)
